# Generated by Django 3.1.3 on 2020-11-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
