# Generated by Django 3.1.3 on 2020-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakedetector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='idioma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='prediccion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
